-- Видалення існуючих таблиць з каскадним видаленням обмежень
DROP TABLE IF EXISTS AUTOMATICRECOMMENDATION CASCADE;
DROP TABLE IF EXISTS INDIVIDUALRECOMMENDATION CASCADE;
DROP TABLE IF EXISTS RECOMMENDATION CASCADE;
DROP TABLE IF EXISTS EDUCATIONALMATERIAL CASCADE;
DROP TABLE IF EXISTS LITERARYWORK CASCADE;
DROP TABLE IF EXISTS MENTOR CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- Створення таблиці "User"
CREATE TABLE "User" (
    USER_ID SERIAL,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    AGE INTEGER,
    EDUCATIONLEVEL VARCHAR(50),
    ISMENTOR BOOLEAN
);

-- Додавання обмеження первинного ключа
ALTER TABLE "User"
ADD CONSTRAINT USER_PK PRIMARY KEY (USER_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE "User"
ALTER COLUMN NAME SET NOT NULL;
ALTER TABLE "User"
ALTER COLUMN EMAIL SET NOT NULL;
ALTER TABLE "User"
ALTER COLUMN AGE SET NOT NULL;
ALTER TABLE "User"
ALTER COLUMN ISMENTOR SET NOT NULL;

-- Додавання обмеження перевірки на вік користувача
ALTER TABLE "User"
ADD CONSTRAINT USER_AGE_POSITIVE CHECK (AGE > 0);

-- Додавання регулярного виразу для перевірки формату email
ALTER TABLE "User"
ADD CONSTRAINT USER_EMAIL_FORMAT CHECK (
    EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
);

-- Створення таблиці MENTOR
CREATE TABLE MENTOR (
    MENTOR_ID SERIAL,
    USER_ID INTEGER,
    EXPERTISEAREA VARCHAR(100),
    YEARSOFEXPERIENCE INTEGER,
    CONTACTINFO VARCHAR(150)
);

-- Додавання обмеження первинного ключа
ALTER TABLE MENTOR
ADD CONSTRAINT MENTOR_PK PRIMARY KEY (MENTOR_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE MENTOR
ALTER COLUMN USER_ID SET NOT NULL;
ALTER TABLE MENTOR
ALTER COLUMN YEARSOFEXPERIENCE SET NOT NULL;

-- Додавання обмеження зовнішнього ключа для зв'язку з таблицею "User"
ALTER TABLE MENTOR
ADD CONSTRAINT MENTOR_USER_FK
FOREIGN KEY (USER_ID) REFERENCES "User" (USER_ID);

-- Додавання перевірки кількості років досвіду ментора
ALTER TABLE MENTOR
ADD CONSTRAINT MENTOR_YEARS_EXPERIENCE_POSITIVE
CHECK (YEARSOFEXPERIENCE > 0);

-- Створення таблиці LITERARYWORK
CREATE TABLE LITERARYWORK (
    WORK_ID SERIAL,
    USER_ID INTEGER,
    TITLE VARCHAR(200),
    TEXT TEXT,
    GENRE VARCHAR(50),
    WORDCOUNT INTEGER,
    CREATIONDATE DATE,
    LASTMODIFIEDDATE DATE
);

-- Додавання обмеження первинного ключа
ALTER TABLE LITERARYWORK
ADD CONSTRAINT LITERARYWORK_PK PRIMARY KEY (WORK_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE LITERARYWORK
ALTER COLUMN USER_ID SET NOT NULL;
ALTER TABLE LITERARYWORK
ALTER COLUMN TITLE SET NOT NULL;
ALTER TABLE LITERARYWORK
ALTER COLUMN TEXT SET NOT NULL;
ALTER TABLE LITERARYWORK
ALTER COLUMN CREATIONDATE SET NOT NULL;

-- Додавання обмеження зовнішнього ключа для зв'язку з таблицею "User"
ALTER TABLE LITERARYWORK
ADD CONSTRAINT LITERARYWORK_USER_FK
FOREIGN KEY (USER_ID) REFERENCES "User" (USER_ID);

-- Додавання перевірки кількості слів у творі
ALTER TABLE LITERARYWORK
ADD CONSTRAINT LITERARYWORK_WORDCOUNT_POSITIVE
CHECK (WORDCOUNT > 0);

-- Додавання регулярного виразу для перевірки жанру
ALTER TABLE LITERARYWORK
ADD CONSTRAINT LITERARYWORK_GENRE_FORMAT
CHECK (GENRE ~ '^[A-Za-z ]+$');

-- Створення таблиці EDUCATIONALMATERIAL
CREATE TABLE EDUCATIONALMATERIAL (
    MATERIAL_ID SERIAL,
    USER_ID INTEGER,
    TITLE VARCHAR(200),
    CONTENT TEXT,
    AUTHOR VARCHAR(100),
    PUBLICATIONDATE DATE
);

-- Додавання обмеження первинного ключа
ALTER TABLE EDUCATIONALMATERIAL
ADD CONSTRAINT EDUCATIONALMATERIAL_PK PRIMARY KEY (MATERIAL_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE EDUCATIONALMATERIAL
ALTER COLUMN USER_ID SET NOT NULL;
ALTER TABLE EDUCATIONALMATERIAL
ALTER COLUMN TITLE SET NOT NULL;
ALTER TABLE EDUCATIONALMATERIAL
ALTER COLUMN CONTENT SET NOT NULL;
ALTER TABLE EDUCATIONALMATERIAL
ALTER COLUMN AUTHOR SET NOT NULL;
ALTER TABLE EDUCATIONALMATERIAL
ALTER COLUMN PUBLICATIONDATE SET NOT NULL;

-- Додавання обмеження зовнішнього ключа для зв'язку з таблицею "User"
ALTER TABLE EDUCATIONALMATERIAL
ADD CONSTRAINT EDUCATIONALMATERIAL_USER_FK
FOREIGN KEY (USER_ID) REFERENCES "User" (USER_ID);

-- Створення таблиці RECOMMENDATION
CREATE TABLE RECOMMENDATION (
    RECOMMENDATION_ID SERIAL,
    USER_ID INTEGER,
    WORK_ID INTEGER,
    CONTENT VARCHAR(500),
    DATE DATE,
    RECOMMENDATIONTYPE VARCHAR(50)
);

-- Додавання обмеження первинного ключа
ALTER TABLE RECOMMENDATION
ADD CONSTRAINT RECOMMENDATION_PK PRIMARY KEY (RECOMMENDATION_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE RECOMMENDATION
ALTER COLUMN USER_ID SET NOT NULL;
ALTER TABLE RECOMMENDATION
ALTER COLUMN WORK_ID SET NOT NULL;
ALTER TABLE RECOMMENDATION
ALTER COLUMN CONTENT SET NOT NULL;
ALTER TABLE RECOMMENDATION
ALTER COLUMN DATE SET NOT NULL;
ALTER TABLE RECOMMENDATION
ALTER COLUMN RECOMMENDATIONTYPE SET NOT NULL;

-- Додавання обмежень зовнішнього ключа для зв'язку з таблицями "User" і LITERARYWORK
ALTER TABLE RECOMMENDATION
ADD CONSTRAINT RECOMMENDATION_USER_FK
FOREIGN KEY (USER_ID) REFERENCES "User" (USER_ID);

ALTER TABLE RECOMMENDATION
ADD CONSTRAINT RECOMMENDATION_WORK_FK
FOREIGN KEY (WORK_ID) REFERENCES LITERARYWORK (WORK_ID);

-- Додавання перевірки на тип рекомендації
ALTER TABLE RECOMMENDATION
ADD CONSTRAINT RECOMMENDATION_TYPE_CHK
CHECK (RECOMMENDATIONTYPE IN ('Individual', 'Automatic'));

-- Створення таблиці INDIVIDUALRECOMMENDATION
CREATE TABLE INDIVIDUALRECOMMENDATION (
    RECOMMENDATION_ID INTEGER,
    MENTOR_ID INTEGER,
    MENTORCOMMENTS VARCHAR(300)
);

-- Додавання обмеження первинного ключа
ALTER TABLE INDIVIDUALRECOMMENDATION
ADD CONSTRAINT INDIVIDUALRECOMMENDATION_PK
PRIMARY KEY (RECOMMENDATION_ID);

-- Додавання обмежень NOT NULL
ALTER TABLE INDIVIDUALRECOMMENDATION
ALTER COLUMN MENTOR_ID SET NOT NULL;
ALTER TABLE INDIVIDUALRECOMMENDATION
ALTER COLUMN MENTORCOMMENTS SET NOT NULL;

-- Додавання обмежень зовнішнього ключа для зв'язку з таблицями RECOMMENDATION і MENTOR
ALTER TABLE INDIVIDUALRECOMMENDATION
ADD CONSTRAINT INDIVIDUALRECOMMENDATION_RECOMMENDATION_FK
FOREIGN KEY (RECOMMENDATION_ID) REFERENCES RECOMMENDATION (RECOMMENDATION_ID);

ALTER TABLE INDIVIDUALRECOMMENDATION
ADD CONSTRAINT INDIVIDUALRECOMMENDATION_MENTOR_FK
FOREIGN KEY (MENTOR_ID) REFERENCES MENTOR (MENTOR_ID);

-- Створення таблиці AUTOMATICRECOMMENDATION
CREATE TABLE AUTOMATICRECOMMENDATION (
    RECOMMENDATION_ID INTEGER
);

-- Додавання обмеження первинного ключа
ALTER TABLE AUTOMATICRECOMMENDATION
ADD CONSTRAINT AUTOMATICRECOMMENDATION_PK
PRIMARY KEY (RECOMMENDATION_ID);

-- Додавання обмеження зовнішнього ключа для зв'язку з таблицею RECOMMENDATION
ALTER TABLE AUTOMATICRECOMMENDATION
ADD CONSTRAINT AUTOMATICRECOMMENDATION_RECOMMENDATION_FK
FOREIGN KEY (RECOMMENDATION_ID) REFERENCES RECOMMENDATION (RECOMMENDATION_ID);
