name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version
      - name: Print Angular Version
        run: |
          npm install -g @angular/cli
          ng version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print PostgreSQL Version
        run: psql --version
